import type { Metadata } from "next";
import {Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins

export const metadata: Metadata = {
  title: "FSW Donalds",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${poppins} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
